baseURL = 'http://team-1280.github.io/electrical-book'
languageCode = 'en-us'
title = 'Team 1280 Electrical Handbook'
theme = "hugo-book"

[params]
BookTheme = 'dark'
BookLogo = 'img/1280-logo.png'


[markup.goldmark.renderer]
unsafe = true
